config/routes.rb
ChiRubyShopsApp::Application.routes.draw do
  
 # resources :shops, :users, :ratings
 # root :to => 'shops#index'
 # match ':controller(/:action(/:id))(.:format)'

 get '/shops', :controller => 'shops', :action => 'index', :as =>  :shops
 get '/shops/:id', :controller => 'shops', :action => 'show', :as => :shop
 
 get '/shops', :controller => 'shops', :action => 'new', :as => :new_shop
 post '/shops', :controller => 'shops', :action => 'create'

 get '/shops/:id/edit', :controller => 'shops', :action => 'edit', :as => :edit_shop 
 put '/shops/:id/', :controller => 'shops', :action => 'update'

 delete 'shops/:id', :controller => 'shops', :action => 'destroy'
 
 
 root :to =>'shops#index'
end

app/models/rating.rb
class Rating < ActiveRecord::Base
  attr_accessible :rating, :comment
  belongs_to :shop
  belongs_to :user

end

app/models/shop.rb
class Shop < ActiveRecord::Base
  attr_accessible :name, :site
  has_many :ratings

  def user_ratings(user)
    #should provide the rating that the user has given to a shop
    #show rating where rating.shop = shop.name
    #ok, now how does rating.shop get created?  Model will need these cols:
    #rating no (1..5), notes txt box, and shop name
  
  end

end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :name, :email, :github_id
  has_many :ratings

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/ratings_controller.rb
class RatingsController < ApplicationController
  
end

app/controllers/shops_controller.rb
class ShopsController < ApplicationController

  def index
    @shops = Shop.all
  end

  def show
    @shop = Shop.find_by_id(params[:id])
  end

  def new
    @shop = Shop.new
  end

  def create
    @shop = Shop.new
    if shop.save
      flash[:success] = "Added"
      redirect_to shops_url
    else
      redirect_to new
    end
  end

  def edit
    @shop = Shop.find_by_id(params[:id])
  end

  def update
    @shop = Shop.find_by_id(params[:id])
    if @shop.update_attributes(params[:shop])
      flash[:success] = "Info Updated"
      redirect_to shop_url
    else
      render 'edit'
    end
  end

  def destroy
    Shop.find_by_id(params[:id]).destroy
    flash[:success] = "Shop has been deleted."
    redirect_to root
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
    @users = User.all
  end

  def show
    @user = User.find_by_id(params[:id])
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(params[:user]) 
    if @user.save
      flash[:success] = "Congrats!  You exist!"
      redirect_to users_url
    else
      render 'new'
    end
  end

  def edit
    @user = User.find_by_id(params[:id])
  end

  def update
    @user = User.find_by_id(params[:id])
    if @user.attributes_update(params[:user])
      flash[:success] = "Profile Updated"
      redirect_to users_url
    else
      render 'edit'
    end
  end

  def delete
    User.find_by_id(params[:id]).destroy
    flash[:success] = "Fine.  We didn't like you anyway."
    redirect_to shops_url
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/ratings_helper.rb
module RatingsHelper
end

app/helpers/shops_helper.rb
module ShopsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ChiRubyShopsApp</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/shops/_form.html.erb
<%= form_for @shop, :html => { :class => 'form-horizontal' } do |f| %>
  <div class="control-group">
    <%= f.label :name, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :name, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :site, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :site, :class => 'text_field' %>
    </div>
  </div>

  <div class="form-actions">
    <%= f.submit nil, :class => 'btn btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                shops_path, :class => 'btn' %>
  </div>
<% end %>

app/views/shops/edit.html.erb
<%- model_class = @shop.class -%>
<h1><%=t '.title', :default => t('helpers.titles.edit', :model => model_class.model_name.human,
                                 :default => "Edit #{model_class.model_name.human}") %></h1>
<%= render :partial => 'form' %>

app/views/shops/index.html.erb
<%- model_class = Shop.new.class -%>
<h1><%=t '.title', :default => model_class.model_name.human.pluralize %></h1>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:name) %></th>
      <th><%= model_class.human_attribute_name(:site) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @shops.each do |shop| %>
      <tr>
        <td><%= link_to shop.name, shop_path(shop) %></td>
        
        <td><%= link_to shop.site, shop.site  %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_shop_path(shop), :class => 'btn btn-mini' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      shop_path(shop),
                      :method => :delete,
                      :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')),
                      :class => 'btn btn-mini btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_shop_path,
            :class => 'btn btn-primary' %>

app/views/shops/new.html.erb
<%- model_class = @shop.class -%>
<h1><%=t '.title', :default => t('helpers.titles.new', :model => model_class.model_name.human,
                               :default => "New #{model_class.model_name.human}") %></h1>
<%= render :partial => 'form' %>

app/views/shops/show.html.erb
<%- model_class = @shop.class -%>
<h1><%=t '.title', :default => model_class.model_name.human %></h1>

<p>
  <strong><%= model_class.human_attribute_name(:name) %>:</strong><br>
  <%= @shop.name %>
</p>
<p>
  <strong><%= model_class.human_attribute_name(:site) %>:</strong><br>
  <%= @shop.site %>
</p>

<div class="form-actions">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              shops_path, :class => 'btn'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_shop_path(@shop), :class => 'btn' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              shop_path(@shop),
              :method => 'delete',
              :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')),
              :class => 'btn btn-danger' %>
</div>

app/views/users/_form.html.erb
<%= form_for @user, :html => { :class => 'form-horizontal' } do |f| %>
  <div class="control-group">
    <%= f.label :name, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :name, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :email, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :email, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :github_id, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :github_id, :class => 'text_field' %>
    </div>
  </div>

  <div class="form-actions">
    <%= f.submit nil, :class => 'btn btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                users_path, :class => 'btn' %>
  </div>
<% end %>

app/views/users/edit.html.erb
<%- model_class = @user.class -%>
<h1><%=t '.title', :default => t('helpers.titles.edit', :model => model_class.model_name.human,
                                 :default => "Edit #{model_class.model_name.human}") %></h1>
<%= render :partial => 'form' %>

app/views/users/index.html.erb
<%- model_class = User.new.class -%>
<h1><%=t '.title', :default => model_class.model_name.human.pluralize %></h1>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:name) %></th>
      <th><%= model_class.human_attribute_name(:email) %></th>
      <th><%= model_class.human_attribute_name(:github_id) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= link_to user.id, user_path(user) %></td>
        <td><%= user.name %></td>
        <td><%= user.email %></td>
        <td><%= user.github_id %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_user_path(user), :class => 'btn btn-mini' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      user_path(user),
                      :method => :delete,
                      :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')),
                      :class => 'btn btn-mini btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_user_path,
            :class => 'btn btn-primary' %>

app/views/users/new.html.erb
<%- model_class = @user.class -%>
<h1><%=t '.title', :default => t('helpers.titles.new', :model => model_class.model_name.human,
                               :default => "New #{model_class.model_name.human}") %></h1>
<%= render :partial => 'form' %>

app/views/users/show.html.erb
<%- model_class = @user.class -%>
<h1><%=t '.title', :default => model_class.model_name.human %></h1>

<p>
  <strong><%= model_class.human_attribute_name(:name) %>:</strong><br>
  <%= @user.name %>
</p>
<p>
  <strong><%= model_class.human_attribute_name(:email) %>:</strong><br>
  <%= @user.email %>
</p>
<p>
  <strong><%= model_class.human_attribute_name(:github_id) %>:</strong><br>
  <%= @user.github_id %>
</p>

<div class="form-actions">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              users_path, :class => 'btn'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_user_path(@user), :class => 'btn' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              user_path(@user),
              :method => 'delete',
              :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')),
              :class => 'btn btn-danger' %>
</div>